In [88]:
import pandas as pd
import numpy as np

# --
# Read Data
# --

In [89]:
data = pd.read_csv("datasets/weatherAUS.csv")

# --
# Data Preprocessing
# --

In [90]:
# data = np.concatenate((X, np.reshape(y, (-1, 1))), axis=1)
t = (data.dtypes == "float64")
num_cols = list(t[t].index)

# Ada Berapa Data Null di Column Numeric?
totalNull = 0
for i in num_cols:
    # print(i, data[i].isnull().sum())
    break
    
# Fill NA
for i in num_cols:
    data[i].fillna(data[i].median(), inplace=True)

In [91]:
lengths = data["Date"].str.len()
lengths.value_counts()

data['Date']= pd.to_datetime(data["Date"])
data['year'] = data.Date.dt.year
data['month'] = data.Date.dt.month
data['day'] = data.Date.dt.day

In [92]:
# Label Encoder
from sklearn.preprocessing import LabelEncoder

# Dapatkan kolom categoricacl
s = (data.dtypes == "object")
object_cols = list(s[s].index)

# Lengkapi kolom yang null
for i in object_cols:
    data[i].fillna(data[i].mode()[0], inplace=True)

# Label Encoder
label_encoder = LabelEncoder()
for i in object_cols:
    data[i] = label_encoder.fit_transform(data[i])

In [83]:
dataNP = data.to_numpy()
idx = []
for i in range(26):
    if i == 0 or i == 22:
        continue
    
    idx.append(i)         

X = dataNP[:, idx]
y = dataNP[:, 22]

[[2 13.4 22.9 ... 2008 12 1]
 [2 7.4 25.1 ... 2008 12 2]
 [2 12.9 25.7 ... 2008 12 3]
 ...
 [41 5.4 26.9 ... 2017 6 23]
 [41 7.8 27.0 ... 2017 6 24]
 [41 14.9 22.6 ... 2017 6 25]]


In [86]:
# Splitting Training and Testing
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = (train_test_split(X, y,test_size = 0.4,random_state=1))

print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(87276, 24)
(58184, 24)
(87276,)
(58184,)


In [87]:
# IQR Detecting Outlier
dataOut = np.concatenate((xtrain, np.reshape(ytrain, (-1, 1))), axis=1)
outliner = 0
for out in range(24):
  colData = dataOut[:,out]
  q1,q3 = np.percentile(colData,[25,75])
  iqr = q3-q1
  lb,ub = q1-1.5*iqr, q3+1.5*iqr

  outliers = dataOut[np.where((colData < lb) | (colData > ub))]
  outliner += len(outliers)

  print("Outliers in Column ", out, " is ", len(outliers))

  dataOut = dataOut[np.where((colData >= lb) & (colData <= ub))]

print("Detected total = ", outliner, " outliers")

pd.DataFrame(data)

xtrain = data[:,0:24]
ytrain = data[:,24]

print(xtrain.shape)
print(ytrain.shape)

Outliers in Column  0  is  0
Outliers in Column  1  is  56
Outliers in Column  2  is  344
Outliers in Column  3  is  17073
Outliers in Column  4  is  18815
Outliers in Column  5  is  20196
Outliers in Column  6  is  0
Outliers in Column  7  is  981
Outliers in Column  8  is  0
Outliers in Column  9  is  0
Outliers in Column  10  is  292
Outliers in Column  11  is  347
Outliers in Column  12  is  445
Outliers in Column  13  is  0
Outliers in Column  14  is  1431
Outliers in Column  15  is  776
Outliers in Column  16  is  6788
Outliers in Column  17  is  1579
Outliers in Column  18  is  166
Outliers in Column  19  is  287
Outliers in Column  20  is  357
Outliers in Column  21  is  0
Outliers in Column  22  is  0
Outliers in Column  23  is  0
Detected total =  69933  outliers


TypeError: '(slice(None, None, None), slice(0, 24, None))' is an invalid key

In [21]:
# Standard Deviation Detecting Outlier
data = np.concatenate((xtrain, np.reshape(ytrain, (-1, 1))), axis=1)

for idx in range(0, 22):
  col_data = data[:, idx]
  
  mean = col_data.mean()
  std = col_data.std()
  lb, ub = mean-(3*std), mean+(3*std)

  data = data[np.where((col_data >= lb) & (col_data <= ub))]

xtrain = data[:, 0:22]
ytrain = data[:, 22]

print(data.shape)
print(xtrain.shape)
print(ytrain.shape)

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [ ]:
# Standard Scaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(original_data)
original_data = scaler.transform(original_data)

In [ ]:
# MinMax Scaler
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(-1,1))
scaler.fit(original_data)
original_data = scaler.transform(original_data)